# ----------------------- #
#      Main Configs       #
# ----------------------- #

title: Sybil's Blog
subtitle: Now is only the beginning~
author: Sybil

#The syntax to highlight code
#monokai, perldoc, default, native
syntax: monokai

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

permalink: pretty
markdown: rdiscount
pygments: true # default python pygments have been replaced by pygments.rb
