# ----------------------- #
#      Main Configs       #
# ----------------------- #

title: A markdown blog in php
author: Sybil
time: 2012

#The syntax to highlight code
#vibrant, zenburn
syntax: vibrant

permalink: pretty
index: archives 

use_cache: false
