# ----------------------- #
#      Main Configs       #
# ----------------------- #

title: Sybil's Blog
subtitle: Now is only the beginning~
author: Sybil

#The syntax to highlight code
#vibrant, zenburn
syntax: vibrant

permalink: pretty
index: index
